#!/bin/sh
#
# PROVIDE: brutefir_drc
# REQUIRE: DAEMON
# KEYWORD: shutdown
#
# Add to /etc/rc.conf:
# brutefir_drc_enable="YES"
#

. /etc/rc.subr

name="brutefir_drc"
rcvar="brutefir_drc_enable"
start_cmd="brutefir_drc_start"
stop_cmd="brutefir_drc_stop"
status_cmd="brutefir_drc_status"

load_rc_config "$name"

: ${brutefir_drc_enable:="NO"}
: ${brutefir_drc_drcsh:="/home/giacomo/DRC/brutefir-conf/drc.sh"}

brutefir_drc_start()
{
	"${brutefir_drc_drcsh}" restore
}

brutefir_drc_stop()
{
	"${brutefir_drc_drcsh}" off
}

brutefir_drc_status()
{
	/home/giacomo/DRC/brutefir-conf/drc-status.sh
}

run_rc_command "$1"
